spring:
  application:
    name: index
  profiles:
    active: h2
  config:
    import:
      - classpath:field-mapping.yml
  # Spring Batch 配置
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  # Quartz 配置
  quartz:
    job-store-type: memory

# 通用配置
index:
  version: 0.1.0
  description: "Index Management System"

# 健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    env:
      enabled: true

# 通用日志配置
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"