#!/bin/bash

# 定义颜色
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# 函数：打印信息
log_info() {
    echo -e "${GREEN}[INFO] $1${NC}"
}

# 函数：打印错误
log_error() {
    echo -e "${RED}[ERROR] $1${NC}"
}

log_info "创建 Quartz 表（Oracle 版本）..."

# 创建 Oracle 版本的 Quartz 表 SQL 脚本
cat > /tmp/quartz_oracle.sql << 'EOF'
-- Quartz 数据库表初始化脚本（Oracle 版本）
-- 基于 Quartz 2.3.2 版本

-- 创建 QRTZ_JOB_DETAILS 表
CREATE TABLE QRTZ_JOB_DETAILS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    JOB_NAME VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    JOB_CLASS_NAME VARCHAR2(250) NOT NULL,
    IS_DURABLE VARCHAR2(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR2(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR2(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

-- 创建 QRTZ_TRIGGERS 表
CREATE TABLE QRTZ_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    JOB_NAME VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    NEXT_FIRE_TIME NUMBER(19) NULL,
    PREV_FIRE_TIME NUMBER(19) NULL,
    PRIORITY NUMBER(10) NULL,
    TRIGGER_STATE VARCHAR2(16) NOT NULL,
    TRIGGER_TYPE VARCHAR2(8) NOT NULL,
    START_TIME NUMBER(19) NOT NULL,
    END_TIME NUMBER(19) NULL,
    CALENDAR_NAME VARCHAR2(200) NULL,
    MISFIRE_INSTR NUMBER(3) NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME, JOB_NAME, JOB_GROUP)
);

-- 创建 QRTZ_SIMPLE_TRIGGERS 表
CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    REPEAT_COUNT NUMBER(19) NOT NULL,
    REPEAT_INTERVAL NUMBER(19) NOT NULL,
    TIMES_TRIGGERED NUMBER(19) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

-- 创建 QRTZ_CRON_TRIGGERS 表
CREATE TABLE QRTZ_CRON_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    TIME_ZONE_ID VARCHAR2(80),
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

-- 创建 QRTZ_SIMPROP_TRIGGERS 表
CREATE TABLE QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    STR_PROP_1 VARCHAR2(512) NULL,
    STR_PROP_2 VARCHAR2(512) NULL,
    STR_PROP_3 VARCHAR2(512) NULL,
    INT_PROP_1 NUMBER(10) NULL,
    INT_PROP_2 NUMBER(10) NULL,
    LONG_PROP_1 NUMBER(19) NULL,
    LONG_PROP_2 NUMBER(19) NULL,
    DEC_PROP_1 NUMBER(13,4) NULL,
    DEC_PROP_2 NUMBER(13,4) NULL,
    BOOL_PROP_1 VARCHAR2(1) NULL,
    BOOL_PROP_2 VARCHAR2(1) NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

-- 创建 QRTZ_BLOB_TRIGGERS 表
CREATE TABLE QRTZ_BLOB_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

-- 创建 QRTZ_CALENDARS 表
CREATE TABLE QRTZ_CALENDARS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    CALENDAR_NAME VARCHAR2(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

-- 创建 QRTZ_PAUSED_TRIGGER_GRPS 表
CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

-- 创建 QRTZ_FIRED_TRIGGERS 表
CREATE TABLE QRTZ_FIRED_TRIGGERS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    ENTRY_ID VARCHAR2(95) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    FIRED_TIME NUMBER(19) NOT NULL,
    SCHED_TIME NUMBER(19) NOT NULL,
    PRIORITY NUMBER(10) NOT NULL,
    STATE VARCHAR2(16) NOT NULL,
    JOB_NAME VARCHAR2(200) NULL,
    JOB_GROUP VARCHAR2(200) NULL,
    IS_NONCONCURRENT VARCHAR2(1) NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NULL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

-- 创建 QRTZ_SCHEDULER_STATE 表
CREATE TABLE QRTZ_SCHEDULER_STATE (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(19) NOT NULL,
    CHECKIN_INTERVAL NUMBER(19) NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

-- 创建 QRTZ_LOCKS 表
CREATE TABLE QRTZ_LOCKS (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    LOCK_NAME VARCHAR2(40) NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);

-- 插入默认锁记录
INSERT INTO QRTZ_LOCKS VALUES('IndexScheduler','STATE_ACCESS');
INSERT INTO QRTZ_LOCKS VALUES('IndexScheduler','TRIGGER_ACCESS');
INSERT INTO QRTZ_LOCKS VALUES('IndexScheduler','JOB_ACCESS');
INSERT INTO QRTZ_LOCKS VALUES('IndexScheduler','CALENDAR_ACCESS');
INSERT INTO QRTZ_LOCKS VALUES('IndexScheduler','MISFIRE_ACCESS');

-- 提交事务
COMMIT;

-- 验证表创建
SELECT 'Quartz tables created successfully' as status FROM DUAL;
SELECT COUNT(*) as table_count FROM user_tables WHERE table_name LIKE 'QRTZ_%';
EOF

# 复制到容器并执行
docker cp /tmp/quartz_oracle.sql index-oracle:/tmp/quartz_oracle.sql
docker exec index-oracle sqlplus system/oracle123@XEPDB1 @/tmp/quartz_oracle.sql

# 验证结果
log_info "验证 Quartz 表是否创建..."
docker exec index-oracle bash -c "echo 'SELECT COUNT(*) FROM user_tables WHERE table_name LIKE '\''QRTZ_%'\'';' | sqlplus -s system/oracle123@XEPDB1"

# 清理临时文件
rm -f /tmp/quartz_oracle.sql

log_info "Quartz 表创建完成！"
