#!/bin/bash

# 定义颜色
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# 函数：打印信息
log_info() {
    echo -e "${GREEN}[INFO] $1${NC}"
}

# 函数：打印错误
log_error() {
    echo -e "${RED}[ERROR] $1${NC}"
}

log_info "创建 Spring Batch 表..."

# 创建 SQL 脚本
cat > /tmp/batch_tables.sql << 'EOF'
-- 创建 Spring Batch 序列
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- BATCH_JOB_INSTANCE 表
CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID NUMBER(19) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19),
    JOB_NAME VARCHAR2(100) NOT NULL,
    JOB_KEY VARCHAR2(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

-- BATCH_JOB_EXECUTION 表
CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19),
    JOB_INSTANCE_ID NUMBER(19) NOT NULL,
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    START_TIME TIMESTAMP(6) DEFAULT NULL,
    END_TIME TIMESTAMP(6) DEFAULT NULL,
    STATUS VARCHAR2(10),
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE VARCHAR2(2500),
    LAST_UPDATED TIMESTAMP(6),
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
    REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

-- BATCH_JOB_EXECUTION_PARAMS 表
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID NUMBER(19) NOT NULL,
    PARAMETER_NAME VARCHAR2(100) NOT NULL,
    PARAMETER_TYPE VARCHAR2(100) NOT NULL,
    PARAMETER_VALUE VARCHAR2(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- BATCH_STEP_EXECUTION 表
CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19) NOT NULL,
    STEP_NAME VARCHAR2(100) NOT NULL,
    JOB_EXECUTION_ID NUMBER(19) NOT NULL,
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    START_TIME TIMESTAMP(6) DEFAULT NULL,
    END_TIME TIMESTAMP(6) DEFAULT NULL,
    STATUS VARCHAR2(10),
    COMMIT_COUNT NUMBER(19),
    READ_COUNT NUMBER(19),
    FILTER_COUNT NUMBER(19),
    WRITE_COUNT NUMBER(19),
    READ_SKIP_COUNT NUMBER(19),
    WRITE_SKIP_COUNT NUMBER(19),
    PROCESS_SKIP_COUNT NUMBER(19),
    ROLLBACK_COUNT NUMBER(19),
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE VARCHAR2(2500),
    LAST_UPDATED TIMESTAMP(6),
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- BATCH_STEP_EXECUTION_CONTEXT 表
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
    REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

-- BATCH_JOB_EXECUTION_CONTEXT 表
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

COMMIT;
EOF

# 复制到容器并执行
docker cp /tmp/batch_tables.sql index-oracle:/tmp/batch_tables.sql
docker exec index-oracle sqlplus system/oracle123@XEPDB1 @/tmp/batch_tables.sql

# 验证表是否创建
log_info "验证 Spring Batch 表是否创建..."
docker exec index-oracle bash -c "echo 'SELECT COUNT(*) as table_count FROM user_tables WHERE table_name LIKE '\''BATCH_%'\'';' | sqlplus -s system/oracle123@XEPDB1"

# 清理临时文件
rm -f /tmp/batch_tables.sql

log_info "Spring Batch 表创建完成！"
