-- Oracle 初始化脚本
-- 注意：此脚本假设已经使用 index_user 用户连接

-- 创建序列
CREATE SEQUENCE distributed_locks_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE idempotency_records_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE job_execution_records_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sample_data_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sample_data_changelog_seq START WITH 1 INCREMENT BY 1;

-- 创建分布式锁表
CREATE TABLE distributed_locks (
    id NUMBER(19) PRIMARY KEY,
    lock_name VARCHAR2(255) NOT NULL UNIQUE,
    instance_id VARCHAR2(255) NOT NULL,
    acquired_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_dl_expires_at ON distributed_locks(expires_at);

-- 创建触发器（自动递增ID）
CREATE OR REPLACE TRIGGER distributed_locks_bir
BEFORE INSERT ON distributed_locks
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT distributed_locks_seq.NEXTVAL INTO :NEW.id FROM DUAL;
  END IF;
END;
/

-- 创建幂等性记录表
CREATE TABLE idempotency_records (
    id NUMBER(19) PRIMARY KEY,
    operation_id VARCHAR2(255) NOT NULL UNIQUE,
    operation_type VARCHAR2(100) NOT NULL,
    instance_id VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NULL,
    error_message CLOB NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ir_operation_type ON idempotency_records(operation_type);
CREATE INDEX idx_ir_status ON idempotency_records(status);
CREATE INDEX idx_ir_start_time ON idempotency_records(start_time);
CREATE INDEX idx_ir_end_time ON idempotency_records(end_time);

-- 创建触发器
CREATE OR REPLACE TRIGGER idempotency_records_bir
BEFORE INSERT ON idempotency_records
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT idempotency_records_seq.NEXTVAL INTO :NEW.id FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER idempotency_records_bur
BEFORE UPDATE ON idempotency_records
FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 创建任务执行记录表
CREATE TABLE job_execution_records (
    id NUMBER(19) PRIMARY KEY,
    job_name VARCHAR2(255) NOT NULL,
    job_instance_id VARCHAR2(255) NOT NULL,
    job_execution_id VARCHAR2(255) NOT NULL UNIQUE,
    instance_id VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NULL,
    parameters CLOB NULL,
    error_message CLOB NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_jer_job_name ON job_execution_records(job_name);
CREATE INDEX idx_jer_instance_id ON job_execution_records(instance_id);
CREATE INDEX idx_jer_status ON job_execution_records(status);
CREATE INDEX idx_jer_start_time ON job_execution_records(start_time);

-- 创建触发器
CREATE OR REPLACE TRIGGER job_execution_records_bir
BEFORE INSERT ON job_execution_records
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    SELECT job_execution_records_seq.NEXTVAL INTO :NEW.id FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER job_execution_records_bur
BEFORE UPDATE ON job_execution_records
FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 创建示例数据表
CREATE TABLE SAMPLE_DATA (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sd_updated_at ON SAMPLE_DATA(UPDATED_AT);
CREATE INDEX idx_sd_status ON SAMPLE_DATA(STATUS);

-- 创建触发器
CREATE OR REPLACE TRIGGER SAMPLE_DATA_bir
BEFORE INSERT ON SAMPLE_DATA
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT sample_data_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER SAMPLE_DATA_bur
BEFORE UPDATE ON SAMPLE_DATA
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- 插入示例数据
INSERT INTO SAMPLE_DATA (NAME, DESCRIPTION, STATUS) VALUES
('John Doe', 'Sample data 1', 'active');

INSERT INTO SAMPLE_DATA (NAME, DESCRIPTION, STATUS) VALUES
('Jane Smith', 'Sample data 2', 'inactive');

INSERT INTO SAMPLE_DATA (NAME, DESCRIPTION, STATUS) VALUES
('Bob Johnson', 'Sample data 3', 'active');

INSERT INTO SAMPLE_DATA (NAME, DESCRIPTION, STATUS) VALUES
('Alice Brown', 'Sample data 4', 'inactive');

INSERT INTO SAMPLE_DATA (NAME, DESCRIPTION, STATUS) VALUES
('Charlie Wilson', 'Sample data 5', 'active');

-- 创建变更日志表
CREATE TABLE SAMPLE_DATA_CHANGELOG (
    ID NUMBER(19) PRIMARY KEY,
    RECORD_ID NUMBER(19) NOT NULL,
    CHANGE_TYPE VARCHAR2(20) NOT NULL,
    CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sdc_record_id ON SAMPLE_DATA_CHANGELOG(RECORD_ID);
CREATE INDEX idx_sdc_changed_at ON SAMPLE_DATA_CHANGELOG(CHANGED_AT);

-- 创建触发器
CREATE OR REPLACE TRIGGER SAMPLE_DATA_CHANGELOG_bir
BEFORE INSERT ON SAMPLE_DATA_CHANGELOG
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT sample_data_changelog_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

-- ===================================
-- Spring Batch 元数据表（Oracle 版本）
-- ===================================

-- 创建 Spring Batch 序列
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- BATCH_JOB_INSTANCE 表
CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID NUMBER(19) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19),
    JOB_NAME VARCHAR2(100) NOT NULL,
    JOB_KEY VARCHAR2(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

-- BATCH_JOB_EXECUTION 表
CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19),
    JOB_INSTANCE_ID NUMBER(19) NOT NULL,
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    START_TIME TIMESTAMP(6) DEFAULT NULL,
    END_TIME TIMESTAMP(6) DEFAULT NULL,
    STATUS VARCHAR2(10),
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE VARCHAR2(2500),
    LAST_UPDATED TIMESTAMP(6),
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
    REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

-- BATCH_JOB_EXECUTION_PARAMS 表
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID NUMBER(19) NOT NULL,
    PARAMETER_NAME VARCHAR2(100) NOT NULL,
    PARAMETER_TYPE VARCHAR2(100) NOT NULL,
    PARAMETER_VALUE VARCHAR2(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- BATCH_STEP_EXECUTION 表
CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19) NOT NULL,
    STEP_NAME VARCHAR2(100) NOT NULL,
    JOB_EXECUTION_ID NUMBER(19) NOT NULL,
    CREATE_TIME TIMESTAMP(6) NOT NULL,
    START_TIME TIMESTAMP(6) DEFAULT NULL,
    END_TIME TIMESTAMP(6) DEFAULT NULL,
    STATUS VARCHAR2(10),
    COMMIT_COUNT NUMBER(19),
    READ_COUNT NUMBER(19),
    FILTER_COUNT NUMBER(19),
    WRITE_COUNT NUMBER(19),
    READ_SKIP_COUNT NUMBER(19),
    WRITE_SKIP_COUNT NUMBER(19),
    PROCESS_SKIP_COUNT NUMBER(19),
    ROLLBACK_COUNT NUMBER(19),
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE VARCHAR2(2500),
    LAST_UPDATED TIMESTAMP(6),
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- BATCH_STEP_EXECUTION_CONTEXT 表
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
    REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

-- BATCH_JOB_EXECUTION_CONTEXT 表
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID NUMBER(19) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- 提交事务
COMMIT;

